In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[ 0.16220376  0.43567439  0.57034645 -0.62547275  1.34248536]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 0.16220376  0.43567439  0.57034645 -0.62547275  1.34248536]


In [6]:
print(np.dot(a,a.T))

2.7349004121470744


In [7]:
a = np.random.randn(5,1)

In [8]:
print(a)

[[-0.99490931]
 [ 1.79430119]
 [ 0.72669296]
 [-0.91429186]
 [-1.69303584]]


In [9]:
print(a.T)

[[-0.99490931  1.79430119  0.72669296 -0.91429186 -1.69303584]]


In [11]:
print(np.dot(a,a.T))

[[ 0.98984453 -1.78516695 -0.72299359  0.90963748  1.68441712]
 [-1.78516695  3.21951675  1.30390604 -1.64051497 -3.03781622]
 [-0.72299359  1.30390604  0.52808266 -0.66440946 -1.23031723]
 [ 0.90963748 -1.64051497 -0.66440946  0.8359296   1.54792889]
 [ 1.68441712 -3.03781622 -1.23031723  1.54792889  2.86637037]]


In [13]:
assert(a.shape == (5,1))